npx truffle-flattener contracts/ERC20/UINK.sol > flatten/UINK.sol
npx truffle-flattener contracts/UinkTreasury.sol > flatten/UinkTreasury.sol
npx truffle-flattener contracts/VoteMining.sol > flatten/VoteMining.sol
npx truffle-flattener contracts/VoteMiningV2.sol > flatten/VoteMiningV2.sol
npx truffle-flattener contracts/Pin.sol > flatten/Pin.sol
npx truffle-flattener contracts/ERC721/UniArtsNFT.sol > flatten/UniArtsNFT.sol
npx truffle-flattener contracts/core/Marketplace.sol > flatten/Marketplace.sol
npx truffle-flattener contracts/core/Auction.sol > flatten/Auction.sol 
npx truffle-flattener contracts/core/AuctionV2.sol > flatten/AuctionV2.sol 
npx truffle-flattener contracts/core/DutchAuction.sol > flatten/DutchAuction.sol
npx truffle-flattener contracts/core/MysteryBox.sol > flatten/MysteryBox.sol 
npx truffle-flattener contracts/core/TrustMarketplace.sol > flatten/TrustMarketplace.sol
npx truffle-flattener contracts/core/TokenLocker.sol > flatten/TokenLocker.sol
npx truffle-flattener contracts/core/TokenLockerStorage.sol > flatten/TokenLockerStorage.sol
npx truffle-flattener contracts/core/TokenLocker.sol > flatten/TokenLocker.sol
npx truffle-flattener contracts/core/MerkleDistributor.sol > flatten/MerkleDistributor.sol
